#define ECHO_DOUBLELIGHT_ON
#define ECHO_DOUBLELIGHT1 * 2
#define ECHO_DOUBLELIGHT3 * fixed3(2,2,2)
#define ECHO_DOUBLELIGHT4 * fixed4(2,2,2,2)
#define ECHO_ADDBEAST_CODE
#define ECHO_DIR_ON
#define ECHO_DIR_ONLYSHADOW
#define ECHO_DIRSPEC_OFF
#define ECHO_DIRDLIGHT_ON
#define ECHO_POINT_ON
#define ECHO_POINTFALLOFF_ON
#define ECHO_POINTDLIGHT_ON
#define ECHO_POINTSPEC_OFF
